tasks:
  - init: |
      python -m venv venv
      source venv/bin/activate
      pip install -r requirements.txt
  - command: |
      source venv/bin/activate
      python manage.py runserver
  
ports:
  - port: 8000
    visibility: private
    onOpen: open-preview
