ports:
- port: 8080
  onOpen: open-preview
tasks:
- init: >
    python3 -m pip install -r requirements.txt &&
    python3 manage.py migrate
  command: >
    echo "from uum_project.settings import *" > uum_project/local_settings.py &&
    echo "ALLOWED_HOSTS = ['*']" >> uum_project/local_settings.py &&
    export DJANGO_SETTINGS_MODULE=uum_project.local_settings &&
    python3 manage.py runserver 0.0.0.0:8080
github:
    prebuilds:
        pullRequestsFromForks: true
